apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    geo-US: "true"
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
        geo-US: "true"
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
