apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    geo-null: "true"
    geo-US: "true"
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
    geo-null: "true"
    geo-US: "true"
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
