apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cat-DB: "true"
    cat-provider: "true"
    cat-content: "true"
    cat-Marketing: "true"
    geo-DE: "true"
    geo-DE: "true"
    cat-DB: "true"
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
