apiVersion: v1
kind: Service
metadata:
  labels:
    geo-US: "true"
    # geo-null: "true"
    geo-EU: "true"
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  
