apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sProhibitedLabels
metadata:
  name: no-db-in-us
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    labelCategory: ["cat-DB"]
    labelCountry: ["geo-US"]
