name: Tilt Geo Extraction

on:
  push:
    paths:
      - 'tilt.json'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JQ
      run: sudo apt-get install jq

    - name: Extract country and update deployment.yaml
      run: |
        # Extract country from tilt.json
        COUNTRIES=$(jq -r '.dataDisclosed[]?.recipients[]?.country' tilt.json)
        
        # Print the extracted countries
        echo "Extracted Countries: $COUNTRIES"
        
        # Check if there are any countries extracted
        if [ -n "$COUNTRIES" ]; then
            # Update deployment.yaml for each country
            for COUNTRY in $COUNTRIES; do
                LABEL="geo-$COUNTRY: \"true\""
                if ! grep -q "$LABEL" dev/deployment.yaml; then
                    awk -v label="$LABEL" '/labels:/ { print; print "    " label; next }1' dev/deployment.yaml > dev/deployment_temp.yaml && mv dev/deployment_temp.yaml dev/deployment.yaml
                fi
            done
        fi

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dev/deployment.yaml
        git diff-index --quiet HEAD || git commit -m "Update deployment.yaml with geo label from tilt.json"
        git push
